version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql-script/01-add-users.sql:/docker-entrypoint-initdb.d/01-add-users.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"